name = "booksync"
compatibility_date = "2024-01-25"
compatibility_flags = ["nodejs_compat"]

# Build configuration
build_command = "cd client && npm install && npm run build"
build_output_directory = "client/dist"

[[r2_buckets]]
binding = "R2"
bucket_name = "booksync"

[functions]
directory = "functions"
node_compat = true