name = "booksync"
compatibility_date = "2024-01-25"
compatibility_flags = ["nodejs_compat"]

# Configure R2 bucket binding
[[r2_buckets]]
binding = "R2"
bucket_name = "booksync"

[env.production]
node_version = "18"

[build]
command = "npm run build"
output_directory = "client/dist"
base_directory = "."
publish_directory = "client/dist"

[site]
bucket = "client/dist"

[functions]
directory = "functions"
node_compat = true

[dev]
port = 5173