name = "booksync"
compatibility_date = "2024-01-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "client/dist"

[[r2_buckets]]
binding = "R2"
bucket_name = "booksync"

[functions]
directory = "functions"
node_compat = true