name = "booksync"
compatibility_date = "2024-01-25"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "R2"
bucket_name = "booksync"

[site]
bucket = "./client/dist"
pages_build_output_dir = "client/dist"

[build]
command = "cd client && npm install && npm run build"

[functions]
directory = "functions"
node_compat = true