name = "booksync"
compatibility_date = "2024-01-25"

# Configure R2 bucket binding
[[r2_buckets]]
binding = "R2"
bucket_name = "booksync"

[site]
bucket = "./client/dist"
include = ["*"]
exclude = ["api/*"]

[build]
command = "npm run build"

[functions]
directory = "functions"

# Environment Variables
[vars]
NODE_ENV = "production"

[env.development]
NODE_ENV = "development"