name = "kindle-upload"
main = "index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "booksync"

[vars]
REDIS_URL = "{{ secrets.REDIS_URL }}"
R2_ENDPOINT = "https://47816ba64eced70ce40d5e757b234acf.r2.cloudflarestorage.com"
R2_ACCESS_KEY_ID = "{{ secrets.R2_ACCESS_KEY_ID }}"
R2_SECRET_ACCESS_KEY = "{{ secrets.R2_SECRET_ACCESS_KEY }}"
R2_BUCKET_NAME = "booksync"
NODE_ENV = "production"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true