name = "kindle-sync"
main = "index.ts"
compatibility_date = "2024-01-26"

# Trigger the worker every 30 minutes
[triggers]
crons = ["*/30 * * * *"]

[vars]
NOTION_OAUTH_CLIENT_ID = ""
NOTION_OAUTH_CLIENT_SECRET = ""
NOTION_REDIRECT_URI = ""
NODE_ENV = "production"
UPSTASH_REDIS_REST_URL = ""
UPSTASH_REDIS_REST_TOKEN = ""
NOTION_TOKEN = ""

# Add your environment variables in .dev.vars file locally
# For production, use wrangler secret:
# wrangler secret put NOTION_OAUTH_CLIENT_ID
# wrangler secret put NOTION_OAUTH_CLIENT_SECRET
# wrangler secret put NOTION_REDIRECT_URI
# wrangler secret put UPSTASH_REDIS_REST_URL
# wrangler secret put UPSTASH_REDIS_REST_TOKEN
# wrangler secret put NOTION_TOKEN