name = "kindle-sync"
main = "index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Trigger the worker every 30 minutes
[triggers]
crons = ["*/30 * * * *"]

[vars]
NOTION_OAUTH_CLIENT_ID = "{{ secrets.NOTION_OAUTH_CLIENT_ID }}"
NOTION_OAUTH_CLIENT_SECRET = "{{ secrets.NOTION_OAUTH_CLIENT_SECRET }}"
NOTION_REDIRECT_URI = "http://localhost:3001/auth/notion/callback"
REDIS_URL = "{{ secrets.REDIS_URL }}"
NODE_ENV = "production"
R2_ENDPOINT = "https://47816ba64eced70ce40d5e757b234acf.r2.cloudflarestorage.com"
R2_ACCESS_KEY_ID = "{{ secrets.R2_ACCESS_KEY_ID }}"
R2_SECRET_ACCESS_KEY = "{{ secrets.R2_SECRET_ACCESS_KEY }}"
R2_BUCKET_NAME = "booksync"