name = "booksync-worker"
main = "src/index.ts"
compatibility_date = "2025-01-26"
compatibility_flags = ["nodejs_compat"]

# Cron triggers for sync and cleanup jobs
[triggers]
crons = [
  "*/30 * * * *",  # Sync job
  "0 0 * * *"      # Cleanup job
]

[[kv_namespaces]]
binding = "OAUTH_STORE"
id = "ff8f1efaccd64d958b29c685b3af8193"

[[kv_namespaces]]
binding = "JOB_STORE"
id = "5a843cd4fb4f4f168b8aeebadef59315"

[[r2_buckets]]
binding = "HIGHLIGHTS_BUCKET"
bucket_name = "highlights-bucket"

[vars]
NOTION_REDIRECT_URI = "https://booksync-worker.az-ajitesh.workers.dev/oauth/callback"
WORKER_HOST = "booksync-worker.az-ajitesh.workers.dev"

# Add your secret variables in .dev.vars or using wrangler secret commands
# wrangler secret put NOTION_CLIENT_ID
# wrangler secret put NOTION_CLIENT_SECRET

[build]
command = "npm run build"

[dev]
port = 8787
