name: Kindle Highlights Sync

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5 hour timeout

    env:
      REDIS_URL: ${{ secrets.REDIS_URL }}
      NOTION_OAUTH_CLIENT_ID: ${{ secrets.NOTION_OAUTH_CLIENT_ID }}
      NOTION_OAUTH_CLIENT_SECRET: ${{ secrets.NOTION_OAUTH_CLIENT_SECRET }}
      NOTION_REDIRECT_URI: ${{ secrets.NOTION_REDIRECT_URI }}
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clear npm cache and install dependencies
        run: |
          cd server
          npm cache clean --force
          npm ci

      - name: Build and run worker
        run: |
          cd server
          # Build TypeScript files
          echo "Building server..."
          npm run build
          echo "Build complete"

          # Set environment variables for GitHub Actions
          export MAX_RUNTIME='18000000'  # 5 hours
          export JOB_TIMEOUT='3600000'   # 1 hour
          export BATCH_SIZE='10'         # Larger batches
          export MAX_HIGHLIGHTS_PER_RUN='100'  # Process more per run

          echo "Starting worker process..."
          npm run worker