name: Kindle Highlights Sync

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5 hour timeout

    env:
      REDIS_URL: ${{ secrets.REDIS_URL }}
      NOTION_OAUTH_CLIENT_ID: ${{ secrets.NOTION_OAUTH_CLIENT_ID }}
      NOTION_OAUTH_CLIENT_SECRET: ${{ secrets.NOTION_OAUTH_CLIENT_SECRET }}
      NOTION_REDIRECT_URI: ${{ secrets.NOTION_REDIRECT_URI }}
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clear npm cache and install dependencies
        run: |
          cd server
          npm cache clean --force
          npm ci

      - name: Build server
        run: |
          cd server
          echo "Building server..."
          npm run build
          echo "Build complete. Checking build directory..."
          ls -la build/src
          
      - name: Verify build output
        run: |
          cd server
          if [ ! -f "build/src/worker.js" ]; then
            echo "Error: worker.js not found in build directory!"
            ls -la build/src
            exit 1
          fi
          
      - name: Run sync process
        run: |
          cd server
          echo "Starting worker process..."
          node -e "
          const { startWorker } = require('./build/src/worker.js');
          
          // Override timeout settings for GitHub Actions
          process.env.MAX_RUNTIME = '18000000';  // 5 hours
          process.env.JOB_TIMEOUT = '3600000';   // 1 hour
          process.env.BATCH_SIZE = '10';         // Larger batches
          process.env.MAX_HIGHLIGHTS_PER_RUN = '100';  // Process more per run
          
          startWorker().catch(err => {
            console.error('Worker failed:', err);
            process.exit(1);
          });"