name: Process Highlights

on:
  repository_dispatch:
    types: 
      - process_highlights
      - process_highlights_test

permissions:
  contents: read
  actions: write

jobs:
  process-highlights:
    if: github.event.action == 'process_highlights'
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 1 hour timeout for file processing

    env:
      REDIS_URL: ${{ secrets.REDIS_URL }}
      NOTION_OAUTH_CLIENT_ID: ${{ secrets.NOTION_OAUTH_CLIENT_ID }}
      NOTION_OAUTH_CLIENT_SECRET: ${{ secrets.NOTION_OAUTH_CLIENT_SECRET }}
      NOTION_REDIRECT_URI: ${{ secrets.NOTION_REDIRECT_URI }}
      NODE_ENV: production

    steps:
      - name: Log Event Details
        run: |
          echo "Received repository_dispatch event"
          echo "Event type: ${{ github.event.action }}"
          echo "Has client payload: ${{ github.event.client_payload != null }}"
          echo "Has fileContent: ${{ github.event.client_payload.fileContent != null }}"
          echo "Has userId: ${{ github.event.client_payload.userId != null }}"

      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd server
          echo "Installing dependencies..."
          npm ci
          echo "Dependencies installed"

      - name: Build
        run: |
          cd server
          echo "Building server..."
          npm run build
          echo "Build complete"

      - name: Process File
        run: |
          cd server
          echo "Starting file processing..."
          node --experimental-vm-modules -e "
          (async () => {
            try {
              console.log('Loading processFileContent function...');
              const { processFileContent } = await import('./build/src/services/processService.js');
              
              console.log('Getting event payload...');
              const fileContent = \`${{ toJSON(github.event.client_payload.fileContent) }}\`;
              const userId = '${{ github.event.client_payload.userId }}';
              
              console.log('Starting file processing with:', {
                userId,
                contentLength: fileContent.length
              });
              
              await processFileContent(userId, fileContent);
              console.log('File processing completed successfully');
            } catch (error) {
              console.error('Failed to process file:', error);
              process.exit(1);
            }
          })();"

  test-webhook:
    if: github.event.action == 'process_highlights_test'
    runs-on: ubuntu-latest
    steps:
      - name: Log Test Event
        run: |
          echo "Received test webhook event"
          echo "Event type: ${{ github.event.action }}"
          echo "Test payload: ${{ toJSON(github.event.client_payload) }}"
      
      - name: Return Success
        run: echo "✅ Webhook test successful"