name: Process Highlights

on:
  repository_dispatch:
    types: 
      - process_highlights
      - process_highlights_test

permissions:
  contents: read
  actions: write

jobs:
  process-highlights:
    if: github.event.action == 'process_highlights'
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 1 hour timeout for file processing

    env:
      REDIS_URL: ${{ secrets.REDIS_URL }}
      NOTION_OAUTH_CLIENT_ID: ${{ secrets.NOTION_OAUTH_CLIENT_ID }}
      NOTION_OAUTH_CLIENT_SECRET: ${{ secrets.NOTION_OAUTH_CLIENT_SECRET }}
      NOTION_REDIRECT_URI: ${{ secrets.NOTION_REDIRECT_URI }}
      NODE_ENV: production

    steps:
      - name: Log Full Event Details
        run: |
          echo "=== Full Event Details ==="
          echo 'Event type: ${{ github.event.action }}'
          echo 'Has client payload: ${{ github.event.client_payload != null }}'
          echo 'Has gistId: ${{ github.event.client_payload.gistId != null }}'
          echo 'Has userId: ${{ github.event.client_payload.userId != null }}'
          echo 'Has databaseId: ${{ github.event.client_payload.databaseId != null }}'
          echo "=========================="

      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd server
          echo "Installing dependencies..."
          npm ci
          echo "Dependencies installed"

      - name: Build
        run: |
          cd server
          echo "Building server..."
          npm run build
          echo "Build complete"

      - name: Fetch Content from Gist
        env:
          GIST_ID: ${{ github.event.client_payload.gistId }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching content from gist..."
          CONTENT=$(curl -L \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/gists/$GIST_ID" \
            | jq -r '.files["content.txt"].content')
          echo "FILE_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "Content fetched and saved to environment"

      - name: Process File
        run: |
          cd server
          echo "Environment variables:"
          echo "FILE_CONTENT length: ${#FILE_CONTENT}"
          echo "Starting file processing..."
          node --experimental-vm-modules processHighlights.js

      - name: Cleanup Gist
        if: always()  # Run even if previous steps fail
        env:
          GIST_ID: ${{ github.event.client_payload.gistId }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Cleaning up gist..."
          curl -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/gists/$GIST_ID"
          echo "Cleanup complete"

  test-webhook:
    if: github.event.action == 'process_highlights_test'
    runs-on: ubuntu-latest
    steps:
      - name: Log Test Event
        run: |
          echo "Received test webhook event"
          echo "Event type: ${{ github.event.action }}"
          echo "Test payload: ${{ toJSON(github.event.client_payload) }}"
      
      - name: Return Success
        run: echo "✅ Webhook test successful"